added SQL query to reviews routes
haikuacademy/B11G03-airbnb-api pull request #24
Opened 2024-02-19 10:06 UTC by MarieBaxter

2024-02-19 14:54 UTC, ynotrusso requested changes
Please see comments inline.

2024-02-19 14:54 UTC, ynotrusso commented on routes/reviewsRoutes.js
> +      house = `WHERE house_id = ${req.query.house}`
Once you've built this query… where are you using it then? It's not in use anywhere, this route always returns all reviews, not just the ones belonging to 1 house.

2024-02-19 14:54 UTC, ynotrusso commented on routes/reviewsRoutes.js
> +      rows.length > 0 ? rows[0] : { error: 'house does not exist' }
Why only return the first review? This is the `/reviews` route, which means it should return an array of reviews, whether it's 0, 1 or many reviews.

2024-02-19 15:15 UTC, MarieBaxter commented on routes/reviewsRoutes.js
> +      rows.length > 0 ? rows[0] : { error: 'house does not exist' }
Ok I fixed this so it returns an array with all the reviews for the house :)

2024-02-19 15:15 UTC, MarieBaxter commented on routes/reviewsRoutes.js
> +      house = `WHERE house_id = ${req.query.house}`
Sorry I don't fully understand your question!

The instructions say you should be able to filter by reviews/?house=x

I tested the code and if you just put /reviews it returns all of the reviews, if you put reviews/?house=x it returns the reviews for the specified house, and if the house_id doesn't exist it return 'house does not exist'.

What am I missing?

2024-02-20 03:23 UTC, ynotrusso approved these changes

2024-02-20 03:23 UTC, merged